# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bd65d33f0351521972802060b45e8c19c8b0565bae3b02d01f986d2e84b0c4848f132859f08df30d9fdf059d73e695a50d6c39e025d2b6e1bf28432373a499f

test:
  secret_key_base: e23dd85bc89089a6f0500d80989a8c6ae5fe162dede4b75a1da17a4d6f2e4a6682cd428c03a381c141ecc3c69eea6cd40c774b3c1c1387de0a63f16eff3da96f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 4bd65d33f0351521972802060b45e8c19c8b0565bae3b02d01f986d2e84b0c4848f132859f08df30d9fdf059d73e695a50d6c39e025d2b6e1bf28432373a499f
